# Este archivo sobreescribe la configuración de docker-compose.yml para desarrollo

services:
  backend:
    # Usa el Dockerfile de desarrollo
    build:
      context: ./backend
      dockerfile: Dockerfile.dev

    # Mapea el puerto del backend a localhost:3000 para acceso directo a la API
    ports:
      - "3000:3000"

    # Volúmenes para hot-reloading
    volumes:
      - ./backend:/app
      # Este volumen anónimo evita que el node_modules local sobreescriba el del contenedor
      - /app/node_modules

    # Comando para iniciar el servidor con nodemon
    command: npm run dev -- --legacy-watch

  frontend:
    # Usa el Dockerfile de desarrollo
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

    # Mapea el puerto del servidor de desarrollo de Angular
    ports:
      - "4200:4200"

    # Volúmenes para hot-reloading
    volumes:
      - ./frontend:/app
      - /app/node_modules

    # Elimina el volumen de nginx.conf que no se usa en desarrollo
    # La sección de "volumes" aquí sobreescribe la del archivo original.

    # Comando para iniciar el servidor de desarrollo de Angular
    # El '-- --host 0.0.0.0' es necesario para que sea accesible fuera del contenedor
    command: npm start -- --host 0.0.0.0 --poll 1000
